### ISSUE TITLE
failed to start HP locally with latest Ruby & Jekyll

### ISSUE THREAD

**Issue by andrejjh** [gbif/hp-gbif-be#1]
I just installed the latest stable Ruby version (3.3.0) and Jekyll to run our GBIF.be HP locally on my mac.
Bundle install went fine, but I got this error with jekyll serve:
(base) [hp-gbif-be] bundle exec jekyll serve                                                                    master 

Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

NOTE: Gem::Platform.match is deprecated; use Gem::Platform.match_spec? or match_gem? instead. It will be removed in Rubygems 4

Gem::Platform.match called from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/index.rb:198.

jekyll 4.1.1 | Error:  undefined method `[]' for nil

/Users/ahe/.rbenv/versions/3.3.0/lib/ruby/3.3.0/logger.rb:384:in `level': undefined method `[]' for nil (NoMethodError)

    @level_override[Fiber.current] || @level

                   ^^^^^^^^^^^^^^^

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/log_adapter.rb:45:in `adjust_verbosity'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/configuration.rb:143:in `config_files'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll.rb:118:in `configuration'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:44:in `configuration_from_options'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:83:in `block (2 levels) in init_with_program'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'

	from /Users/ahe/.rbenv/versions/3.3.0/bin/jekyll:25:in `load'

	from /Users/ahe/.rbenv/versions/3.3.0/bin/jekyll:25:in `<top (required)>'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'

	from /Users/ahe/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'

	from /Users/ahe/.rbenv/versions/3.3.0/bin/bundle:25:in `load'

	from /Users/ahe/.rbenv/versions/3.3.0/bin/bundle:25:in `<main>'

Any idea what could that be? I did not touch anything in the 'hp-gbif-be' directory cloned from gitHub.
Maybe some old incompatible gems on my laptop.
It is a long time I haven't work with Ruby and gems.

**Comment by andrejjh** [comment]
Has mentioned in this [post](https://stackoverflow.com/questions/77851863/bundle-exec-jekyll-serve-not-working-locally), I tried to downgrade Ruby to 3.2.3, but it failed with another error:

(base) [hp-gbif-be] bundle exec jekyll serve                                                                master  ✭ ✱
bundler: failed to load command: jekyll (/Users/ahe/.rbenv/versions/3.2.3/bin/jekyll)
/Users/ahe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/jekyll-liquify-0.0.3/lib/jekyll-liquify.rb:15:in `<top (required)>': uninitialized constant LiquidFilter (NameError)

Liquid::Template.register_filter(LiquidFilter)
                                 ^^^^^^^^^^^^
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/runtime.rb:60:in `require'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/runtime.rb:55:in `each'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/runtime.rb:55:in `block in require'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/runtime.rb:44:in `each'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/runtime.rb:44:in `require'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler.rb:187:in `require'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/jekyll-4.1.1/lib/jekyll/plugin_manager.rb:53:in `require_from_bundler'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/jekyll-4.1.1/exe/jekyll:11:in `<top (required)>'
	from /Users/ahe/.rbenv/versions/3.2.3/bin/jekyll:25:in `load'
	from /Users/ahe/.rbenv/versions/3.2.3/bin/jekyll:25:in `<top (required)>'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `load'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/cli/exec.rb:23:in `run'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/cli.rb:492:in `exec'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/ahe/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
	from /Users/ahe/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
	from /Users/ahe/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
(

**Comment by MortenHofft** [comment]
Perhaps this can help? https://github.com/gbif/hp-swiss-bif/issues/1

**Comment by andrejjh** [comment]
Found a solution! The problem was this : an incompatibility between Ruby 3.2 and Liquid 4.0.3. see [here](https://github.com/github/pages-gem/issues/859)
Solution: use Liquid 4.0.4 instead of 4.0.3

**Comment by andrejjh** [comment]
Now I can run my Hosted portal locally with 'bundle exec jekyll serve'
