### ISSUE TITLE
Occurrences  menu in dutch(NL)

### ISSUE THREAD

**Issue by andrejjh** [gbif/hp-gbif-be#18]
For some reason, the menu title of the [Occurrence search page in dutch](https://gbif.biodiversity.be/nl/occurrence/search) says: 
'{NUMBER, plural, 0 {Voorkomens} one {Voorkomen} other {Voorkomens}' instead of 'Occurrences' in french and english.
This part of the code was not customised, and I don't know how to fix it.
![Screenshot 2024-08-12 at 14 14 50](https://github.com/user-attachments/assets/2737ed88-2894-4222-a153-b2cf49f42769)

Any idea?

**Comment by MortenHofft** [comment]
A bad translation. I’ve changed it to Voorkomens
https://crowdin.com/editor/gbif-portal/817/en-nl?view=comfortable&filter=basic&value=0#q=occurrences
 
Are you a translator already? If not it might be useful for you so you can edit translations, add missing etc.

You and others that would like a dutch version have to provide the translations

**Comment by andrejjh** [comment]
Fixed via Crowdin
